### ISSUE TITLE
bash-completion not sorted/stable

### ISSUE THREAD

**Issue by olafhering** [2ion/mpv-bash-completion#18] opened 2017-10-24 15:16 UTC
* mpv version: mpv-0.27.0
 * mpv-bash-completion version (or link to package): mpv-bash-completion-3.3.15
 * Operating system: Tumbleweed

---------
The generated file usr/share/bash-completion/completions/mpv differs with each rebuild, the list of options is apparently not sorted. The mpv binary itself is stable, its content does not differ between clean rebuilds.

It is unclear where to add a sort(). Weird that "mpv --list-options" is used, which likely has a stable output. Still, the _mpv_fargs/_mpv_pargs list order differs.

**Comment by olafhering** [comment] 2017-10-24 15:21
This does not happen every time for some reason. Still, the build logs show a republish:

[https://build.opensuse.org/package/show/multimedia:apps/mpv](https://build.opensuse.org/package/show/multimedia:apps/mpv)

**Comment by 2ion** [comment] 2017-10-24 15:57
The order of entries varies since the keys are retrieved from a Lua
table using the pairs() iterator, and the order in which keys are
retrieved from the hash table is unspecified.  This is the default
behaviour of key-value iteration over hash tables in Lua. Retrieving the
keys in any sorted order requires extra work, but it is possible.

Why do you perceive this as an issue? Because if makes precise diffing
difficult or impossible?

**Comment by olafhering** [comment] 2017-10-24 16:06
If a package differs after build, compared to the formerly built binaries, it has to be republished. That wastes resources. For that reason why we try to reduce the amount of unpredictable changes by sorting relevant parts of package content.

Debian sells this as [https://reproducible-builds.org/](https://reproducible-builds.org/)

**Comment by 2ion** [comment] 2017-10-24 16:16
On Tue, Oct 24, 2017 at 09:06:49AM -0700, Olaf Hering wrote:
> If a package differs after build, compared to the formerly built
> binaries, it has to be republished. That wastes resources. For that
> reason why we try to reduce the amount of unpredictable changes by
> sorting relevant parts of package content.
>
> Debian sells this as [https://reproducible-builds.org/](https://reproducible-builds.org/)

I see. Getting stable output from a set of fixed inputs would be a good
improvement. I'll address this before the next release.

**Closed** 2017-10-24 16:54 UTC
Labels: enhancement

**Comment by 2ion** [comment] 2017-10-24 16:58
I believe the problem is fixed (see the referenced commit). I'll tag a
new release sometime soon.
